### ISSUE TITLE
Can we increase the line thickness of the default text. Pretty hard to read for me.

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#102]
It actually looks fine in Chrome. It's in firefox that things are very light.

![screenshot from 2015-10-11 10 47 53](https://cloud.githubusercontent.com/assets/536941/10416230/8ca0c920-7005-11e5-8810-3e890f628149.png)

**Comment by evz** [comment]
This is also the case for me but I'm pretty sure it's related to the fact that we're on Linux and the default Sans Serif font that is used is kinda thin. That said, I would support finding a compromise between what you and I (and other Linux users see) and what the "normals" see.
