### ISSUE TITLE
Show "trending" committees

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#110]
Illinois Sunshine is now getting enough traffic to that the site patterns are revealing some interesting things:

![screenshot from 2015-11-16 10 52 03](https://cloud.githubusercontent.com/assets/536941/11188409/4d292fa0-8c50-11e5-8573-dd6cafa7b1b9.png)

Would be fun to add a "trending" committees section to home page.

**Comment by evz** [comment]
We might be able to repurpose something like this: http://pythonhosted.org/Flask-Track-Usage/ to automate this a bit.

**Comment by evz** [comment]
Another facet to this might be "new" committees, especially in the build up to the election. This would be as simple as showing the recent Statements of Organization.
