### ISSUE TITLE
Urgent: Donations not updated for yesterday...

### ISSUE THREAD

**Issue by sarahbrune** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#111]
We can't access donations from the 18th. Not sure if something went wrong with the SBOE data or upload? 

We need to do our IL Sunshine update today, but can't until we know that everything is up to date. Let me know what's up as soon as you can

**Comment by evz** [comment]
Good news: You should have updated data pretty soon.
¯\_(ツ)_/¯ news: I'm still trying to figure out what actually happened. I'll make sure to keep an eye on this over the next few days to see if the SBOE is perhaps not updating their files on the same schedule as they were previously.

**Comment by evz** [comment]
Everything is updated now.

**Comment by sarahbrune** [comment]
Thanks!!

Do you know what happened??

**Comment by evz** [comment]
Not yet. I'll leave this issue open until I figure it out. I've added some logging to the overnight job that updates everything to see if I can see anything.

**Comment by sarahbrune** [comment]
Sound good. thanks for the update.

**Comment by sarahbrune** [comment]
that was not meant to sound sarcastic I really do mean thank you <3

**Comment by evz** [comment]
Ha! The voice in my head assumed an absence of sarcasm but now that I re-read that the other way I think I might like it better :grin:
