### ISSUE TITLE
Shorten mailing list funnel by embedding mailing list contact form

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#112]
http://support2.constantcontact.com/articles/FAQ/1538

**Comment by sarahbrune** [comment]
You want me to grab the embed code instead of the link?

**Comment by sarahbrune** [comment]
<link rel='stylesheet' type='text/css' href='
https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/css/signup-form.css
'>
<div class="ctct-embed-signup" style="font: 1rem/1.5 Helvetica Neue, Arial,
sans-serif; font-size-adjust: none; font-stretch: normal;
-webkit-font-smoothing: antialiased;">
   <div style="border-radius: 5px; color: rgb(91, 91, 91);
background-color: rgb(232, 232, 232);">
       <span id="success_message" style="display: none;">
           <div style="text-align: center;">Thanks for signing up!</div>
       </span>
       <form name="embedded_signup" class="ctct-custom-form Form" action="
https://visitor2.constantcontact.com/api/signup" method="POST"
data-id="embedded_signup:form">
           <h2 style="margin: 0px;">Sign up for Illinois Sunshine News!</h2>
           <p>Sign up to get timely, accurate, and relevant Illinois
campaign finance data delivered to your inbox.</p>
           
           <input name="ca" type="hidden"
value="6f34e6d0-2785-46e7-bd2f-726113816806" data-id="ca:input">
           <input name="list" type="hidden" value="1254692819"
data-id="list:input">
           <input name="source" type="hidden" value="EFD"
data-id="source:input">
           <input name="required" type="hidden"
value="list,email,first_name" data-id="required:input">
           <input name="url" type="hidden" value="" data-id="url:input">
           <p data-id="Email Address:p" ><label class="ctct-form-required"
data-id="Email Address:label" data-name="email">Email Address</label>
<input name="email" type="text" maxlength="80" value="" data-id="Email
Address:input"></p>
           <p data-id="First Name:p" ><label class="ctct-form-required"
data-id="First Name:label" data-name="first_name">First Name</label> <input
name="first_name" type="text" maxlength="50" value="" data-id="First
Name:input"></p>
           <button class="Button ctct-button Button--block
Button-secondary" type="submit" data-enabled="enabled">Sign Up</button>
        <div><p class="ctct-form-footer">By submitting this form, you are
granting: Illinois Campaign for Political Reform, 36 W. Randolph S.,
Chicago, Illinois, 60601, United States, http://www.ilcampaign.org
permission to email you. You may unsubscribe via the link found at the
bottom of every email.  (See our <a href="
http://www.constantcontact.com/legal/privacy-statement"
target="_blank">Email Privacy Policy</a> for details.) Emails are serviced
by Constant Contact.</p></div>
       </form>
   </div>
</div>
<script type='text/javascript'>
   var localizedErrMap = {};
   localizedErrMap['required'] =   'This field is required.';
   localizedErrMap['ca'] =    'An unexpected error occurred while
attempting to send email.';
   localizedErrMap['email'] =    'Please enter your email address in
name@email.com format.';
   localizedErrMap['birthday'] =   'Please enter birthday in MM/DD format.';
   localizedErrMap['anniversary'] =  'Please enter anniversary in
MM/DD/YYYY format.';
   localizedErrMap['custom_date'] =  'Please enter this date in MM/DD/YYYY
format.';
   localizedErrMap['list'] =    'Please select at least one email list.';
   localizedErrMap['generic'] =   'This field is invalid.';
   localizedErrMap['shared'] =   'Sorry, we could not complete your
sign-up. Please contact us to resolve this.';
   localizedErrMap['state_mismatch'] = 'Mismatched State/Province and
Country.';
 localizedErrMap['state_province'] = 'Select a state/province';
   localizedErrMap['selectcountry'] =  'Select a country';
   var postURL = 'https://visitor2.constantcontact.com/api/signup';
</script>
<script type='text/javascript' src='
https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/js/signup-form.js
'></script>
