### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by ICPR** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#129]
On the [homepage search bar](http://www.illinoissunshine.org/), we would like the text to read "Search for names of candidates, committees, and donors in Illinois"

We would also like this text to be darker than it currently is.

![screen shot 2016-06-17 at 10 20 30 am](https://cloud.githubusercontent.com/assets/19154788/16155467/2f1e4086-3475-11e6-828f-387836a77439.png)

**Comment by ziegegeist** [comment]
Just sent a pull request. I wasn't sure how to make it darker without messing anything up, but I did change the text.
