### ISSUE TITLE
Is there still an API?

### ISSUE THREAD

**Issue by joyhchen** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#174]
I'm wondering if an API is still available or if it was taken down. Thanks! I also ask because this documentation template is still up. https://github.com/Illinois-Campaign-for-Political-Reform/illinois-sunshine/blob/master/sunshine/templates/api-documentation.html

**Comment by sarahbrune** [comment]
Hi Joy,

We do not make the API publicly available, however, we work with some
public entities to share the dataset with them. Let me know if you would
like to discuss this further.

*Sarah Brune*
Executive Director

Illinois Campaign for Political Reform
500 N Dearborn St, Suite 518
Chicago, IL 60654
ilcampaign.org
illinoissunshine.org <http://www.illinoissunshine.org>

o 312.436.1274 | c 402.719.6287
