### ISSUE TITLE
Citizens for Unes shows up twice in the full committee list

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#37]
![screenshot from 2015-07-15 20 35 38](https://cloud.githubusercontent.com/assets/536941/8713657/225d6c08-2b31-11e5-8b93-070b8d72c15d.png)

(24 and 25)

**Comment by fgregg** [comment]
Same for Citizens for Durkin

**Comment by evz** [comment]
This, unfortunately, is because those committees support more than one candidate. How would you recommend resolving that? Comma separated list of candidates supported? There are certain committees that support quite a few candidates so that might get unwieldy.

**Comment by fgregg** [comment]
In a committee view I expect just to see committees. Why do we need one per candidate?

**Comment by evz** [comment]
So, should we not be showing associated candidates in that view? The thinking there was that since they are candidate committees, one might like to see the candidate(s). Most of the time, I guess that's easy enough to derive from the name of the committee.

**Comment by fgregg** [comment]
Well, I think if you want to show candidates, show candidates in a
candidates view. It's confusing that you are showing multiple committees on
a page you are calling the committees page.
