### ISSUE TITLE
Potential for memory errors

### ISSUE THREAD

**Issue by evz** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#45]
There's a case where a search query that returns a lot of results can cause the application to run out of memory. This happens here: https://github.com/datamade/illinois-sunshine/blob/master/sunshine/api.py#L155 

The reason I originally decided to go with that and then just return a slice of those results based upon the limit and offset parameters was because I also wanted to return a total number of rows that the query resulted in (so that we can easily paginate them in the UI). There are better ways of doing this.

**Comment by evz** [comment]
This is still occasionally happening when the Googlebot hits a link that goes to a search results page. Generally speaking, it's when the search is for something that includes single letters like ``F & T Partnership``. Under the hood, I am breaking the search term on spaces and then turning it into a series of wildcard expressions like so ``F:* & T:* & Partnership:*`` (punctuation is stripped before I execute the search so the ampersands there are part of the [PostgreSQL full text search syntax](http://www.postgresql.org/docs/9.4/static/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES))

Anyhoo, I think we ought to figure out how to do this in a more efficient way.

**Comment by fgregg** [comment]
You are doing an expensive form of stemming:
https://en.wikipedia.org/wiki/Stemming It looks like postgresql does this
already:
http://blog.lostpropertyhq.com/postgres-full-text-search-is-good-enough/

**Comment by evz** [comment]
Perhaps, but I'm not sure it does Stemming for names. Which is what the most common searches are. Searching for "Ed Burke" does not return "Edward M Burke" unless I do the wildcard junk.

**Comment by fgregg** [comment]
Sounds like you don't actually want to do stemming, but you want to do
synonyms.

Is personal names really the case you want to handle? (Your current
approach won't work for Will/Bill)

**Comment by fgregg** [comment]
What you want are Hypocoristics

https://en.wiktionary.org/wiki/Appendix:English_given_names#Hypocoristics_of_English_given_names

**Comment by evz** [comment]
OK. We'll work this into the next phase. For the moment, I'll just keep an eye on the errors and if we're getting a lot that are effecting actual people, I'll do something about it. So far, it's only effected the Googlebot.

**Comment by evz** [comment]
It turns out that there is a subtle bug here in the way that Jinja is rendering URLs that we are sending to the search page, how that gets potentially munged by a browser and/or the web server and then how that is being parsed by the javascript on the search page that actually triggers the search. 

Observations so far are that if I tell Jinja to urlencode the term portion of the URL (so, turn something like `/search/?term=Bruce Rauner` into `/search/?term=Bruce%20Rauner`) either ones browser or the web server encodes it again turning it into `/search/?term=Bruce%2520Rauner` (encoding the `%` as `%25`). From there on it's kinda broken. However, if I don't urlencode those strings, things like `/search/?term=G & A Construction and Development Inc.` get broken on the `&` because the web server thinks it's the beginning of another query parameter. 

I mainly have seen this kind of issue logged to sentry as the result of a Googlebot crawling the site so I'm pretty sure that no humans have actually seen this issue yet. I'll meditate on this and see if there is a compromise someplace.
