### ISSUE TITLE
Consistently right justify money amounts

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#56]
Money amounts are not justified on
- any of the tables in a commitee view: http://www.illinoissunshine.org/committees/support-independent-maps-29503/
- Any of the tables in a search view

**Comment by fgregg** [comment]
On committee pages, Top donations and Top Expenditures are still left justified.

**Comment by derekeder** [comment]
I played around with that and they ended up being too close to the date column. Will have to do some additional styling to get them to look good.
