### ISSUE TITLE
Useful definition of election cycles

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#82]
From http://www.elections.il.gov/downloads/campaigndisclosure/pdf/contribution%20limits.pdf

For Political Party Committees, Political Action Committees, Independent Expenditure Committees and Ballot Initiative Committees, an election cycle is a calendar year (beginning January 1 and ending on December 31 of each calendar year.) However, for Candidate Political Committees, the election cycle depends on what office is being sought by the candidate supported by the committee. For each of four
different candidate designations, there are two possible election cycles:
# Candidate Political Committee election cycles:

For a committee supporting a candidate to be elected at a General Primary Election or General Election, the election cycle is either:
1. January 1 (following the General Election for the office sought) through the date of the General Primary Election (for the office sought), or
2. the day after the General Primary Election (for the office sought) through December 31 (following the General Election.)

For a committee supporting a candidate to be elected at a Consolidated Primary Election or Consolidated Election, the election cycle is either:
1. July 1 (following a Consolidated Election) through the date of the Consolidated Primary Election, or
2. the day after the Consolidated Primary Election through June 30 (following a Consolidated Election.)

For a committee supporting a candidate for the General Assembly, the election cycle is either:
1. January 1 (following a General Election) through the date of the next General Primary Election, or
2. the day after a General Primary Election through December 31 (following a General Election.)

For a committee supporting a candidate for a (judicial) retention election, the election cycle is either:
1. January 1 (following the General Election when the candidate was elected) through the date the candidate files a declaration of intent to seek retention, or
2. the day after the candidate files a declaration of intent to seek retention through December 31 (following the retention election.

**Comment by fgregg** [comment]
So what elections are the city elections?

**Comment by fgregg** [comment]
@sarahbrune, welcome to github!!!! So, could explain how local candidates like mayors and city councilors fit into this.

**Comment by sarahbrune** [comment]
I believe that "consolidated elections" are city elections. I know that is at least the case for Chicago.

**Comment by fgregg** [comment]
yay!!!

**Comment by sarahbrune** [comment]
Yep! I want to look into this more next week when we work on our spring legislation, because I find the election cycles very generally confusing...
