### ISSUE TITLE
Add business logic to detect discrepancies

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#87]
(Total donations-total expenditures) should roughly equal (current assets - current debts)

For the Illinois State Medical PAC there's are about 1.5 million discrepancy. 

http://www.illinoissunshine.org/committees/70/

@evz, @sarahbrune, why might that be?

**Comment by fgregg** [comment]
Oh.. duh it's probably #86

**Comment by fgregg** [comment]
Sorry, no it isn't. If we didn't count that $1.2 mil investment expenditure as an expenditure, there would be a 2.7 mil discrepancy

**Comment by fgregg** [comment]
It's also not necessarily due to the fact that our data only starts sometimes in the 1990s. In Feb 1990, they had net 200K

**Comment by fgregg** [comment]
There's a 500K discrepancy for this committee : http://www.illinoissunshine.org/committees/20758/

**Comment by fgregg** [comment]
Okay, https://github.com/datamade/illinois-sunshine/commit/71bbe51acc5154e665091ec6b7a06468fba655c5 fixed a lot.

Now for alvarez's committee, there is only a $1,400 discrepancy.

**Comment by evz** [comment]
Something tells me the answer to this involves in-kind contributions. The
D2 Reports don't add those in as actual money (because it isn't) but we may
be counting those on one side and not the other (or something). Anyways,
just a theory. I'll dig deeper when I get a minute.
