### ISSUE TITLE
On committee pages we report cumulative donations since the founding date of the committee, not since we start having data

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#88]
This committee was started in 1970, but the first report from them that's available on the ISBE website is from 1990 http://www.elections.il.gov/CampaignDisclosure/D2Pre.aspx?id=4831

How are you calculating the cumulative donation and expenditure amounts. Are your numbers really going back to 1974 as we say here: http://www.illinoissunshine.org/committees/70/

**Comment by fgregg** [comment]
attn @evz

**Comment by evz** [comment]
No. We just need to put in a conditional that displays the founding date of
the committee in that spot only if it is newer than the oldest date that we
have data for.

**Comment by fgregg** [comment]
We should change that to the oldest date that we have data for.
