### ISSUE TITLE
Where are the 'supported candidates' info coming from for the IL Democratic Party

### ISSUE THREAD

**Issue by fgregg** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#97]
On http://www.illinoissunshine.org/committees/6239/ we show three supported candidates, but I can't see  that info on ISBE's site.

**Comment by evz** [comment]
When a committee spends money, they have the option (and in the case of independent expenditures the obligation as far as I know) to say if they spent the money in support of or in opposition to a candidate (which is indicated in a separate free text field so we can't directly link them to candidate records). That's where the names in the tables on the committee pages come from. In the case of "Drury" these are the records that we have in the expenditures table that match: 

```
 amount  |     expense_name      | candidate_name |    expended_date    | supporting | opposing 
----------+-----------------------+----------------+---------------------+------------+----------
 14677.25 | Frye-Williamson Press | Drury          | 2012-11-04 00:00:00 | t          | f
  5123.44 | US Postmaster         | Drury          | 2012-10-25 00:00:00 | t          | f
  5123.44 | US Postmaster         | Drury          | 2012-10-29 00:00:00 | t          | f
  2561.72 | US Postmaster         | Drury          | 2012-10-30 00:00:00 | t          | f
 14677.25 | Frye-Williamson Press | Drury          | 2012-11-04 00:00:00 | t          | f
(5 rows)
```

(huh, looks like there's a duplicate in there ... sigh)

Anyways, that's how we get those names.
